# This is a basic workflow to help you get started with Actions

name: Update Documents from last race

# Controls when the workflow will run
on:
  schedule:
    - cron: '10 10 06 03 *'
    - cron: '10 10 20 03 *'
    - cron: '10 10 03 04 *'
    - cron: '10 10 01 05 *'
    - cron: '10 10 08 05 *'
    - cron: '10 10 22 05 *'
    - cron: '10 10 29 05 *'
    - cron: '10 10 05 05 *'
    - cron: '10 10 19 06 *'
    - cron: '10 10 03 07 *'
    - cron: '10 10 10 07 *'
    - cron: '10 10 24 07 *'
    - cron: '10 10 31 07 *'
    - cron: '10 10 28 08 *'
    - cron: '10 10 04 09 *'
    - cron: '10 10 18 09 *'
    - cron: '10 10 25 09 *'
    - cron: '10 10 09 10 *'
    - cron: '10 10 23 10 *'
    - cron: '10 10 30 10 *'
    - cron: '10 10 06 11 *'
    - cron: '10 10 19 11 *'
    - cron: '10 10 27 11 *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Install WGET
        run: |
          sudo apt update && sudo apt install wget -y
      - name: Update documents
        run: |
          wget -A pdf -l=1 --mirror "https://www.fia.com/documents/championships/fia-formula-one-world-championship-14/season/season-2023-2042"
      - name: Add updated files    
        run: |
           git config user.name "GH Runner"
           git add *
           git commit --allow-empty -m "After race automatic update"
           git push
          
